//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment
    {
        public int appid { get; set; }
        public string pname { get; set; }
        public string email { get; set; }
        public Nullable<long> contact { get; set; }
        public Nullable<System.DateTime> appdate { get; set; }
        public string dept { get; set; }
        public string doctor { get; set; }
        public string msg { get; set; }
    }
}
