//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int cid { get; set; }
        public string guestname { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
        public string comments { get; set; }
        public Nullable<int> blogid { get; set; }
    
        public virtual blog blog { get; set; }
    }
}
